project:
  type: book

book:
  title: "SynComMethods"
  author: "高春辉"
  date: "2023/8/10"
  chapters:
    - index.qmd
    - write-an-equation.qmd
    - strain-and-combination.qmd
    - culture-method.qmd
    - metabolic-model.qmd
    - ecological-model.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



