project:
  type: book

book:
  title: "SynComMethods"
  author: "高春辉"
  date: "2023/8/10"
  chapters:
    - index.qmd
    - write-math-equation.qmd
    - write-chemical-equation.qmd
    - technical-writing-with-quarto.qmd
    - strain-and-combination.qmd
    - culture-method.qmd
    - metabolic-model.qmd
    - ecological-model.qmd
    - glv-model.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>



