project:
  type: book

execute:
  freeze: auto

book:
  title: "SynComMethods"
  author: "高春辉"
  date: "2023/8/10"
  cover-image: cover.png
  chapters:
    - index.qmd
    - write-math-equation.qmd
    - write-chemical-equation.qmd
    - technical-writing-with-quarto.qmd
    - strain-and-combination.qmd
    - culture-method.qmd
    - metabolic-model.qmd
    - ecological-model.qmd
    - glv-model.qmd
    - strain-specific-pcr.qmd
    - design-primer.qmd
    - design-specific-primer-with-cailab-utils.qmd
#    - design-primer-with-unikmer.qmd
    - kmer-facilitated-primer-design.qmd
    - mathematical-optimization.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  pdf:
    documentclass: scrreprt
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-in-header:
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}


