project:
  type: book

execute:
  freeze: auto

book:
  title: "SynComMethods"
  author: "高春辉"
  date: now
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: 科学写作
      chapters:
        - write-math-equation.qmd
        - write-chemical-equation.qmd
        - technical-writing-with-quarto.qmd
    - part: 微生物培养
      chapters:
        - strain-and-combination.qmd
        - culture-method.qmd
    - part: 代谢网络
      chapters:
        - metabolic-model.qmd
        - learn-fba.qmd
        - MICOM.qmd
    - part: 生态模型
      chapters:
        - ecological-model.qmd
        - glv-model.qmd
    - part: 引物设计
      chapters:
        - strain-specific-pcr.qmd
        - design-primer.qmd
        - design-specific-primer-with-cailab-utils.qmd
        - design-primer-with-unikmer.qmd
        - kmer-facilitated-primer-design.qmd
    - part: 数学基础
      chapters:
        - mathematical-optimization.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-after-body:
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  pdf:
    documentclass: scrreprt
    mermaid-format: png
    extract-media: images
    fig-width: 7
    fig-asp: 0.618
    warning: false
    message: false
    include-in-header:
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage[version=4]{mhchem}
            \usepackage{siunitx}


